[project]
name = "vara"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.0.1",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
